export const projects = [
    {
        id: 1,
        image: "",
        name: "Safety Path",
        desc: "Online sales page for custom-designed signs",
        url: "https://safetypath.com",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 2,
        image: "",
        name: "Reveal Group",
        desc: "",
        url: "https://revealgroup.com/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 3,
        image: "",
        name: "Lacoste Viet Nam",
        desc: "",
        url: "https://lacoste.com.vn/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 4,
        image: "",
        name: "It's take a village",
        desc: "",
        url: "https://yourvillage.com.au/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 5,
        image: "",
        name: "Integral Lighting",
        desc: "",
        url: "https://www.integrallighting.com.au",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 6,
        image: "",
        name: "Conecta App",
        desc: "",
        url: "https://app.conecta.com.au",
        skills: ["NuxtJS", "Typescript", "Axios", "Greensock"],
    },
    {
        id: 7,
        image: "",
        name: "Conecta",
        desc: "",
        url: "https://conecta.com.au/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 7,
        image: "",
        name: "Boss Hunting",
        desc: "",
        url: "https://www.bosshunting.com.au/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 8,
        image: "",
        name: "Bongiorno",
        desc: "",
        url: "https://bongiorno.com.au/",
        skills: ["Wordpress", "Javascript", "Ajax", "Greensock"],
    },
    {
        id: 9,
        image: "",
        name: "Mintlabo",
        desc: "",
        url: "https://mintlabo.com/",
        skills: ["Wordpress", "Elementer"],
    },
];
