import "./globals.scss";
import '@splidejs/react-splide/css/core';

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
    title: "Brian Do",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
